@PiPlateRelayServer_HostAddress = http://192.168.1.36:5055
@boardNumber = 0
@relayNumber = 1


GET {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/info
Accept: application/json

###
GET {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/hardwareVersion
Accept: application/json

###
GET {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/firmwareVersion
Accept: application/json

###
POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/ledOn
Accept: application/json

###

POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/ledOff
Accept: application/json

###

POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/ledToggle
Accept: application/json

###

POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/relay/{{relayNumber}}/on
Accept: application/json

###

POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/relay/{{relayNumber}}/off
Accept: application/json

###

POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/relay/{{relayNumber}}/toggle
Accept: application/json

###

GET {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/relay/status
Accept: application/json

###

GET {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/relay/{{relayNumber}}/status
Accept: application/json

###

POST {{PiPlateRelayServer_HostAddress}}/board/{{boardNumber}}/relay/reset
Accept: application/json

###